on:
  push:
    branches:
      - master

name: ARM64 R-CMD-check 

jobs:
  R-CMD-check:
    runs-on: ubuntu-20.04
    env: 
      CONTAINER_R_LIB_PATH: /home/runner/work/_temp/_github_home/r_library
      CONTAINER_HOME_PATH: /home/runner/work/_temp/_github_home
    steps:
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64
          
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set R options
        run: |
          mkdir -p ${CONTAINER_HOME_PATH}
          echo "options(Ncpus = 2)" > ${CONTAINER_HOME_PATH}/.Rprofile
          echo "R_LIBS=\${HOME}/r_library:\${R_LIBS}" > ${CONTAINER_HOME_PATH}/.Renviron

      - name: Create library location if not restored from cache
        #if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p ${CONTAINER_R_LIB_PATH} 

      - name: Install developer tools packages
        uses: docker://arm64v8/r-base:latest
        with:
          args: >
            Rscript -e "toInstall <- setdiff(c('BiocManager', 'remotes', 'rcmdcheck', 'tinytest'), installed.packages()[,'Package'])" -e "if(length(toInstall)) { install.packages(toInstall) }"  
            
      - name: Check installed packages
        uses: docker://arm64v8/r-base:latest
        with:
          args: >
            Rscript -e "rcmdcheck::rcmdcheck(path = 'examplePKG', check_dir = Sys.getenv('HOME'))"
            